shuheiktgw/go-travis

builds.go
builds_integration_test.go

Solve https://github.com/shuheiktgw/go-travis/issues/1

Add BranchName option to BuildsByRepositoryOption

---

requests.go

Solves #2 by allowing more complex objects.

Change Config type from string to interface{}

---

travis.go

Allow base HTTP client to be changed.

---

travis.go
travis_test.go

Enables to override UserAgent.

Allow User-Agent to be set.

---

CHANGELOG.md
version.go

Bumps up to v0.1.9

---

README.md

Update features on README

---

repositories.go
repositories_integration_test.go
repositories_test.go

- Add newly created attributes to `Repository`
- Add `RepositoryOption` to support eager loading on repository endpoint

Add eager loading support for the repository endpoint

---

repositories.go
repositories_integration_test.go
repositories_test.go

- Add support  for the repositories  endpoint.

Add support for the repositories endpoint

---

init_integration_test.go
users.go
users_integration_test.go
users_test.go

- Rename `user.go` -> `users.go`.
- Add `UserOption` struct to support eager loading on user endpoint.

Add support for eager loadin on user endpoint

---

organizations.go
organizations_integration_test.go
organizations_test.go

- Add some props to `Organization` struct.
- Add `OrganizationOption` struct.
-  Rename `getOrganizationsResponse` -> `organizationsResponse`.

Add support for eager loading on organizations endpoint

---

active.go
active_integration_test.go
active_test.go

- Rename `getActiveResponse` -> activeResponse`.
- Add `ActiveOption` to support eager loading on active endpoint.

Add support for eager loading on active endpoint

---

beta_features.go
beta_features_integration_test.go
beta_features_test.go

- Rename `getBetaFeaturesResponse` -> `betaFeaturesResponse`.
- Add `Delete` method for `BetaFeaturesService`.

Add Delete method for BetaFeaturesService

---

crons.go
crons_integration_test.go
crons_test.go

- Rename `getCronsResponse` -> `cronsResponse`.
- Add `CronOption` to support eager loading on cron/crons endpoint.

Support eager loading on cron/crons endpoint

---

env_vars.go

Rename getEnvVarsResponse to envVarsResponse

---

installations_integration_test.go
installations_test.go
installatios.go

- Add `InstallationOption` to support eager loading on installation endpoint.

Support eager loading on installation endpoint

---

logs.go
logs_integration_test.go
logs_test.go

- Rename `FindByJob` to `FindByJobId`.
- Add `DeleteByJobId`.

Add DeleteByJobId

---

messages.go
messages_integration_test.go
messages_test.go
travis.go

Support messages endpoints

---

requests.go
requests_integration_test.go
requests_test.go

- Rename `ListRequestsOption` -> `RequestsOption`.
- Rename `getRequestsResponse` -> `requestsResponse `.
- Add `RequestOption`.

Support eager loading on request/requests endpoints

---

requests.go

It seems they've added new props to Request struct.
https://developer.travis-ci.com/resource/request#standard-representation

Add BaseCommit and HeadCommit props to Request struct

---

repositories.go
repositories_integration_test.go
repositories_test.go

- Add `Migrate` action to RepositoryService.

Add Migrate action to RepositoryService

---

beta_migration_requests.go
beta_migration_requests_integration_test.go
beta_migration_requests_test.go
travis.go

Support beta_migration_requests endpoint

Support beta_migration_requests endpoint

---

init_integration_test.go
key_pair_integration_test.go

Add integration tests for https://github.com/shuheiktgw/go-travis/pull/51.

Add integration tests for key pair endpoints

---

branches_integration_test.go
env_vars_integration_test.go
owners_integration_test.go
repositories_integration_test.go

Fix integration tests fmts

---

CHANGELOG.md
version.go

Bumps up to v0.2.2

---

env_vars.go
env_vars_integration_test.go
env_vars_test.go

Travis released the env var per branch feature.
https://changelog.travis-ci.com/environment-variables-per-branch-109051
And API v3 supports the option as well.
https://developer.travis-ci.com/resource/env_var#Env%20var
This PR makes the option available on go-travis.

Add "branch" option to Env vars

---

config.go
init_integration_test.go
jobs.go
jobs_integration_test.go

Fix https://github.com/shuheiktgw/go-travis/issues/65. Support config props of Job.

Add config props to Job struct

---

CHANGELOG.md
version.go

- https://github.com/shuheiktgw/go-travis/pull/67
- https://github.com/shuheiktgw/go-travis/pull/66

Bumps up to v0.2.4

---

.github/workflows/test.yml
README.md

I'm dissatisfied with the quality of Travis CI API, so very sadly I've decided to move this project to Github Actions.

Good bye Travis

---

CHANGELOG.md
scripts/bump.sh
version.go

Bumps up to v0.3.0
